### ISSUE TITLE
How do I integrate and use this plugin? 

### ISSUE THREAD

**Issue by hashtagsheep** [getsetgames/Fabric#1]
Currently I try to get this plugin running in our project but I didn't have much success yet. Is there an easy step by step guide?

Best

**Comment by derekvanvliet** [comment]
@chbecher I added setup instructions to the readme:

https://github.com/getsetgames/Fabric/blob/master/README.md

**Comment by hashtagsheep** [comment]
Nice work and thank you very much :)
